### PR TITLE
polish logging, error handling, and routing

### LINKED ISSUE #17: use logger

### LINKED ISSUE #19: error handling
- deal with some common errors in new endpoints
- use a middleware to catch all unhandled error to prevent app crash

### PR DESCRIPTION
**Pull request by shunjizhan**
## Change
Did some polish so that relayer is more prod ready:
1) replace console.log with pino logging, which is more friendly for prod
2) use a unified router for handling router related endpoints
3) previously return data is a little random, it can has many different keys. So I slightly changed it to using a more conventional way, so all return data is the following shape:
```
{
  data?    // if request success, result data goes here
  error?   // if request failed, error info goes here
  msg?     // additional info (usually for error)
}
```

Note that 2 and 3 only applied to router endpoints, `/relay` and `/shouldRelay` is not touched to avoid breaking changes.

Also there was no clear distinguish between "failed request" and "success request with answer no", after this update they are more clearly separated:
- when should not route by `/shouldRouteXxx`, it's considered as a "success request" whose result is "no", so there is no `res.error`
- if a para is missing, then it's a failed request, and error info is in `res.error`

fix #19 
fix #17 

## Test
all tests still pass

### CODE REVIEW

File: src/relay.ts [hunk 1]
```diff
@@ -46,25 +44,30 @@ export const relay = async (request: any, response: any): Promise<void> =>  {
...
-    response.status(200).json(receipt);
+    return response.status(200).json(receipt);
   } catch (e) {
-    console.log(`Relay Failed ❌: ${relayInfo}`);
-    console.error(e);
-    return response.status(500).json({ error: e, msg: 'Unable to relay this request.' });
+    logger.debug(relayInfo, 'Relay Failed ❌');
+    logger.error(e);
+
+    return response.status(200).json({
```
Comment (shunjizhan) [inline src/relay.ts:59]: use 200 to be consistent with router endpoints. current 500 actually broke womrhole prod UI when there is relay error

File: src/middlewares/error.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+export class NoRouteError extends Error {
+  constructor(message: string) {
+    super(message);
+    this.name = 'NoRouteError';
+  }
+}
+
+/* --------------------
+   we use a consistent 200 for all responses to mark a "successfull conversation"
```
Comment (xlc) [inline src/middlewares/error.ts:12]: this could be a bit confusing?

there are expected errors and unexpected errors and I am ok for expected errors to be 200 (e.g. route a not supported asset) but unexpected error should be 4xx or 5xx (unexpected internal server error should be 5xx)

this ensures we have visibility on errors as we can check datadog for error rate and setup alers if needed

Comment (shunjizhan) [reply src/middlewares/error.ts]: sure let's use the standard error code

**Review by xlc — APPROVED** [review]
